series: Basic OpenGL with GLFW
title: Basic Particle System
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Write a simple cpu based particle system.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: Sprite Batching